digit = "0".."9" ;
number = { digit } ;

TableStmt = "[", number, "]" ;
IncStmt = "+" ;
DecStmt = "-" ;
MulStmt = "*" ;
DivStmt = "/" ;
PrintStmt = "." ; 
MovRightStmt = ">" ;
MovLeftStmt = "<" ;
LoopStmt = "{", Block, "}", ["(", number | "$", ")"] ;
DefStmt = "[", number, "]" ;
IfStmt = "?", "(", number | "$", ")", Block, Eos ;
GotoStmt = "@", "(", number | "$", ")" ;
SaveStmt = "$" ;
PrintAsciiStmt = "&" ;
CopyStmt = "=", "(", number | "$", ")" ;
ModuloStmt = "%" ;
DefFnStmt = ":", "(", number, ")", Block, Eos ;
CallFnStmt = "^", "(", number, ")" ;
PrintNewlStmt = "_" ;
FlipStmt = "~" ;
Eos = ";" ;

SourceFile = TableStmt, "\n" | "\r", Block ;
Block = { Statement } ;
Statement = TableStmt | IncStmt | DecStmt | MulStmt | DivStmt | PrintStmt | MovRightStmt | MovLeftStmt | LoopStmt | FlipStmt
            | DefStmt | IfStmt | GotoStmt | SaveStmt | PrintAsciiStmt | CopyStmt | ModuloStmt | DefFnStmt | CallFnStmt | PrintNewlStmt ;